#!/bin/bash
# issue: https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1529

for package in jupyter-contrib-nbextensions jupyter-latex-envs; do
    location=$(pip show ${package} | grep 'Location:' | cut -d ':' -f2 | xargs)
    for i in $(pip show -f ${package}); do
        if [ "${i: -3}" = ".py" ]; then
            sed -i 's/template_path/template_paths/g' "${location}/${i}"
        fi
    done
done